#!/bin/bash
#
# Generator for decidim.org (data/cities.yml)
#
# Input CSV with this structure:
#   organization,type,status,notes,country,url,image,repo,weight
#   "Ajuntament de Barcelona",,,,,,,,"https://www.decidim.barcelona/","/images/partners/logo_partner_ajbcn.jpg",,,,,
#
# Output example:
# - barcelona
#   - name: Barcelona
#   - url: https://www.decidim.barcelona/
#   - image: /images/cityhalls/logo_aj_barcelona.jpg
# - helsinki
# (...)

slugify () {
  # https://stackoverflow.com/a/49035906
  echo "$1" | iconv -t ascii//TRANSLIT | sed -r s/[~\^]+//g | sed -r s/[^a-zA-Z0-9]+/-/g | sed -r s/^-+\|-+$//g | tr A-Z a-z
}

should_home () {
  weight=$1
  [[ $weight -le 30 ]] && echo true || echo false
}

transform_type () {
  type=$1
  case $type in
    "Ayuntamiento") echo "city" ;;
    "Región"|"Diputación"|"Otra institución/organización"|"Diputacions/Governs/Consorcis") echo "region" ;;
    "Federación"|"Cooperativa"|"Universidad"|"Otra institución/organización"|"Plan Comunitario"|"Otra administración/organismo"|"Red de trabajo") echo "org" ;;
    *) echo "org" ;;
  esac
}

INPUT='data.csv'
OLDIFS=$IFS
IFS=,

# we need to order the data by weight 
[ ! -f $INPUT ] && { echo "$INPUT file not found"; exit 99; }
[ $# -eq 0 ] && { echo "No arguments supplied. Pass 'cities' or 'monitor'"; exit 99; }
WEIGHTED_INPUT=/tmp/data.csv
sort -n -t"," -k9 $INPUT > $WEIGHTED_INPUT

if [ $1 == "monitor" ] ; then
  OUTPUT=tmp/cities.ex
else
  OUTPUT=data/cities.yml
fi

echo "# This is an autogenerated file." > $OUTPUT
echo "# If you want your installation to be on decidim.org," >> $OUTPUT
echo "# you can create an issue on https://github/decidim/decidim.org" >> $OUTPUT
echo "# or say hi at hola [at] decidim.org" >> $OUTPUT
echo "" >> $OUTPUT

while read organization type status notes country url image repo weight
do
  if [ $1 == "monitor" ] ; then
    if ( [ $status == "Producción" ] || [ $status == "Pre-producción" ] ) && [ ! -z $url ] ; then
      slug=$(slugify $organization)
      echo "    \"$slug\" => %{
        name: \"$name\",
        url: \"$url\",
        repo: \"$repo\"
     }," >> $OUTPUT
    fi
  else
    if [ $status == "Producción" ] && [ ! -z $url ] && [ ! -z $image ] ; then
      slug=$(slugify $organization)
      otype=$(transform_type $type)
      home=$(should_home $weight)
      [[ ! -f source/images/cityhalls/$image ]] && echo "image source/images/cityhalls/${image} doesn't exists" && exit 1
      echo "- ${slug}:" >> $OUTPUT
      echo "  name: \"${organization}"\" >> $OUTPUT
      echo "  url: ${url}" >> $OUTPUT
      echo "  image: /images/cityhalls/${image}" >> $OUTPUT
      echo "  type: ${otype}" >> $OUTPUT
      echo "  home: ${home}" >> $OUTPUT
    fi
  fi
done < $WEIGHTED_INPUT
IFS=$OLDIFS
